services:
  - type: web
    name: omantel-netinsight
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate

    startCommand: >
    bash -lc "
    echo '=== START COMMAND RUNNING ===';
    pwd;
    ls -la;
    echo '=== LIST data/ ===';
    ls -la data || true;
    echo '=== RUN SEED ===';
    python manage.py seed_from_excel --verbosity 2;
    echo '=== SEED DONE ===';
    gunicorn omantel.wsgi:application
    "


    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
