services:
  - type: web
    name: omantel-netinsight
    env: python
    plan: free
    region: singapore
    
    buildCommand: |
      cd omantel && pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && (python manage.py seed_from_excel --verbosity 2 || echo "Seed completed or skipped")

    startCommand: cd omantel && python -m gunicorn omantel.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: omantel-netinsight
          property: host
