# Generated by Django 5.2.7 on 2025-10-27 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=100)),
                ('signal_strength', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Offline', 'Offline')], max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='regions.region')),
            ],
            options={
                'verbose_name': 'Tower',
                'verbose_name_plural': 'Towers',
            },
        ),
    ]
