# Generated by Django 5.2.7 on 2025-12-23 22:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('region', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_type', models.CharField(blank=True, default='Other', max_length=50, null=True)),
                ('duration_hours', models.FloatField(default=0)),
                ('impact_level', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_via', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('data_gb', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('terrain_type', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_temp_c', models.FloatField(blank=True, null=True)),
                ('avg_humidity_pct', models.FloatField(blank=True, null=True)),
                ('rainy_season_effect', models.CharField(blank=True, max_length=200, null=True)),
                ('signal_interference_level', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('kpi_date', models.DateField()),
                ('download_mbps', models.FloatField(blank=True, null=True)),
                ('upload_mbps', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('uptime_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_users', models.IntegerField(blank=True, default=0, null=True)),
                ('business_users', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_data_gb_per_day', models.FloatField(blank=True, default=0.0, null=True)),
                ('peak_usage_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('age_group_dominant', models.CharField(blank=True, max_length=50, null=True)),
                ('usage_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_id', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('tower_type', models.CharField(blank=True, max_length=100, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('power_source', models.CharField(blank=True, max_length=100, null=True)),
                ('operational_status', models.CharField(blank=True, max_length=100, null=True)),
                ('max_capacity_users', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(blank=True, default='', max_length=100)),
                ('status_after', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_logs', to='dashboard.tower')),
            ],
        ),
        migrations.CreateModel(
            name='TowerStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='dashboard.tower')),
            ],
        ),
    ]
