# Generated by Django 5.2.7 on 2025-10-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.RemoveField(
            model_name='region',
            name='avg_usage_gb',
        ),
        migrations.RemoveField(
            model_name='region',
            name='complaints_count',
        ),
        migrations.RemoveField(
            model_name='region',
            name='total_users',
        ),
    ]
